### ISSUE TITLE
Jitter in realtime loop

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ros-interface-ethercat#11]
The ROS realtime loop occasionally exhibits large amounts of jitter. Specifically, two consecutive frames can be spaced up to 20ms apart. The problem seems to be worse when rxplot is running. Also, robot_monitor might contribute to the problem.

![host_jitter_2013_05_31](https://f.cloud.github.com/assets/3330595/591119/d5003218-c9fa-11e2-97fc-499831a6a01e.png)

In the attached image, vertical bars represent 1ms frames. 99% of them are exactly 1ms apart, but some are 3ms, 6ms, or even 19ms apart.

**Comment by ugocupcic** [comment]
Driver running on core2 @ 1.8GHz. May be due to that. Try on beefier pc? Still need to look at optimisation etc...

**Comment by ugocupcic** [comment]
from Rich:

That is outside the actual timing loop, though - do you mean the one at 501?

The problem Hugo is seeing is that inside the loop (lines 402--526)
occasionally there is a 20ms delay.

The clock should definitely have decent resolution unless someone
compiled the kernel with silly settings.

What I was wondering about was whether any of ec.update() or
publishDiagnostics() or the rtpublisher->trylock() were blocking on
something else Is it holding a lock somewhere? The easy way to test for this
would be to time the execution of each call with a clock_gettime()
before and after, and check if it was ever >10mS.

**Comment by ugocupcic** [comment]
may be look at this too: http://ros-users.122217.n3.nabble.com/RT-ROS-EtherCAT-td3651577.html

**Comment by ugocupcic** [comment]
https://help.ubuntu.com/community/UbuntuStudio/RealTimeKernel

**Comment by ugocupcic** [comment]
This is not visible on a more recent computer (tested on both my laptop and my desktop - both hugely overloaded). 

After a discussion with Hugo, we'll drop that one (as it's more a design decision than a bug - not using rt kernel). We still need to make the SPI protocol more robust to packet drop as it's an issue for SPI.
