### ISSUE TITLE
sr_external_dependencies builds are failing due to generating read only files

### ISSUE THREAD

**Issue by tfoote** [shadow-robot/sr-ros-interface-ethercat#119]
The builds are generating read only files which cannot be cleaned up: http://54.183.26.131:8080/view/Ibin_uT64/job/Ibin_uT64__sr_external_dependencies__ubuntu_trusty_amd64__binary/18/console

This is causing the build to fail on all platforms.

**Comment by ugocupcic** [comment]
Update to use @andriy's new release process.

**Comment by ugocupcic** [comment]
@AndriyPt is this fixed now ?

**Comment by AndriyPt** [comment]
@ugocupcic yes, I have removed all read-only files
