### ISSUE TITLE
[sr_tactile_sensor_controller] publishers do not respect publish_rate

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-ros-interface-ethercat#127]
there are two different last_publish_time_ one for the controller, that gets initialized correctly,
https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/indigo-devel/sr_tactile_sensor_controller/include/sr_tactile_sensor_controller/sr_tactile_sensor_controller.hpp#L64
 but also one in the parent class of the publishers that does not get initialized and stays at zero
https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/indigo-devel/sr_tactile_sensor_controller/include/sr_tactile_sensor_controller/sr_tactile_sensor_publisher.hpp#L31

The publishers have currently no access to the last_publish_time of the controller and hence have a time starting at zero which is always below the current walltime and so each update fires a publish, hence not respecting the rate.

I suggest to have an argument to the init of the publishers to pass the initial time as the last_publish_time of the controller

**Comment by toliver** [comment]
Good point! I think that's a good idea.

We should also set `initialized_` to false in the `stop()` function, so that the publishers are re-instantiated with the correct `last_publish_time` after a controller start().

Alternatively we could add a start(time) function to the publishers (called from the start of the controller).

The `last_publish_time` variable in the controller should be deleted.

**Comment by guihomework** [comment]
The main issue is that the controller cannot pass the time directly when starting as the publishers are initialized only in the first update. We cannot easily change that behavior because at controller init the type of tactile is not yet known.

I can find a nice way to clean that up following your suggestions and do a PR. 

I agree that last_publish_time should not be at two places.

**Comment by toliver** [comment]
But your idea of passing the time in the init function of the publishers would work, so I think that should be the way to go.
