### ISSUE TITLE
2 hand resets when one hand starts up in a 2 realtime loop setup

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-ros-interface-ethercat#247]
We always run 2 realtime loops each in one namespace (rh and lh), each controlling one hand.
we start first the right hand, which finishes with the motor reset and controller params loading
then we start the left hand, which finishes with the motor reset but this motor resets ALSO resets the right hand.

I don't believe we had this behavior in the past, and a dual reset is not desirable. Indeed it happened from time to time that one palm driver fails (red blinking LED) and one needs to restart this driver, but maybe the second hand is running and holding an object, one do not want one hand to resets the second one.

I suppose the problem is in the python script https://github.com/shadow-robot/sr_core/blob/a345602152771526ebdd61ff0f52393077f1622d/sr_utilities/scripts/sr_utilities/calibrate_hand_finder.py#L46 ALL reset services of both hands.

I think one should take into account the fact that the calibrate_hand_finder might be started from a namespace and then only list the service in that namespace.
I will try add this and create a PR

**Comment by toliver** [comment]
Fixed by https://github.com/shadow-robot/sr_core/pull/188
