### ISSUE TITLE
tactile topics publish at 111Hz instead of supposed 100Hz

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr-ros-interface-ethercat#47]
We recorded /tactile and /joint_states and realized they were not the same speed although there should be both at 100Hz

```
rostopic hz /rh/tactile
subscribed to [/rh/tactile]
average rate: 111.090
    min: 0.008s max: 0.009s std dev: 0.00022s window: 106
average rate: 111.105
    min: 0.008s max: 0.009s std dev: 0.00023s window: 217
```

The loop counter is counting until 9 not until 10 in sr06.cpp and sr08.cpp and maybe somewhere else.
I created a patch that I tested, and will pull request that immediately

**Comment by ugocupcic** [comment]
Ah! Good catch thanks.
